# Generated by Django 3.2.9 on 2021-12-07 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='coin_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='paper_trading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_balance', models.FloatField()),
                ('balance', models.FloatField()),
                ('enter_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper_trading', to=settings.AUTH_USER_MODEL, verbose_name='paper trading')),
            ],
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('l', 'long'), ('s', 'short')], max_length=1, verbose_name='type')),
                ('amount', models.FloatField(verbose_name='token amount')),
                ('status', models.CharField(choices=[('s', 'sell'), ('b', 'buy'), ('w', 'working'), ('c', 'close')], max_length=1, verbose_name='trade status')),
                ('entert_price', models.FloatField()),
                ('enter_date', models.DateTimeField(auto_now_add=True)),
                ('stoploss', models.FloatField(blank=True, null=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('coin1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin1', to='api.coin_list')),
                ('coin2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin2', to='api.coin_list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='api.paper_trading', verbose_name='position')),
            ],
        ),
        migrations.CreateModel(
            name='close_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('close_price', models.FloatField()),
                ('position', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='close_date_position', to='api.position', verbose_name='position')),
            ],
        ),
    ]
