# Generated by Django 3.2.9 on 2021-12-17 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch_listItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin1', models.CharField(max_length=20)),
                ('coin2', models.CharField(max_length=20)),
                ('watch_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchList_item', to='api.watch_list', verbose_name='Watch list')),
            ],
        ),
    ]
