# Generated by Django 3.2.9 on 2021-12-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='oreder_reach_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
