# Generated by Django 3.2.9 on 2021-12-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='coin1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='coin2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='coin',
            field=models.CharField(max_length=20),
        ),
    ]
