# Generated by Django 3.2.9 on 2021-12-08 07:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='enter_date',
            new_name='oreder_set_date',
        ),
        migrations.RemoveField(
            model_name='position',
            name='stoploss',
        ),
        migrations.RemoveField(
            model_name='position',
            name='take_profit',
        ),
        migrations.AddField(
            model_name='position',
            name='oreder_reach_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='position',
            name='status',
            field=models.CharField(choices=[('w', 'Working'), ('d', 'Done'), ('c', 'close')], max_length=1, verbose_name='trade status'),
        ),
        migrations.AlterField(
            model_name='position',
            name='trade_type',
            field=models.CharField(choices=[('b', 'Buy'), ('s', 'Sell')], max_length=1, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='position_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('b', 'Buy'), ('s', 'Sell')], max_length=1, verbose_name='type')),
                ('amount', models.FloatField(verbose_name='token amount')),
                ('status', models.CharField(choices=[('p', 'Pending'), ('w', 'Working'), ('d', 'Done'), ('c', 'close')], max_length=1, verbose_name='trade status')),
                ('oreder_reach_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('stoploss', models.FloatField(blank=True, null=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('in_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_position', to='api.position', verbose_name='in_position')),
            ],
        ),
    ]
