# Generated by Django 3.2.9 on 2021-12-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper_trading',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
