# Generated by Django 3.2.9 on 2021-12-14 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='coin amount')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coinName', to='api.coin_list')),
                ('paper_trading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wallet', to='api.paper_trading', verbose_name='wallet')),
            ],
        ),
    ]
