# Generated by Django 3.2.9 on 2021-12-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position_option',
            name='trade_type',
            field=models.CharField(choices=[('t', 'Take Profit'), ('s', 'Stop loss'), ('w', 'Working')], default='w', max_length=1, verbose_name='trade type'),
        ),
        migrations.AlterField(
            model_name='position_option',
            name='oreder_reach_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position_option',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('w', 'Working'), ('d', 'Done'), ('c', 'close')], max_length=1, verbose_name='trade status'),
        ),
    ]
