# Generated by Django 3.2.9 on 2021-12-15 23:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch_list',
            name='coin',
            field=models.CharField(default=datetime.datetime(2021, 12, 15, 23, 33, 12, 625765, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
