# Generated by Django 3.2.9 on 2021-12-18 17:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211217_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='order_type',
            field=models.CharField(choices=[('m', 'Market'), ('l', 'Limit')], default=datetime.datetime(2021, 12, 18, 17, 34, 38, 585373, tzinfo=utc), max_length=1, verbose_name='order type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='trade_type',
            field=models.CharField(choices=[('b', 'Buy'), ('s', 'Sell')], max_length=1, verbose_name='trade type'),
        ),
    ]
