# Generated by Django 3.2.9 on 2021-12-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_paper_trading_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper_trading',
            name='balance',
            field=models.FloatField(blank=True, default=models.FloatField(), null=True),
        ),
    ]
