# Generated by Django 3.2.9 on 2021-12-15 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='coin1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='coin2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='coin',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Watch_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin1', models.CharField(max_length=20)),
                ('coin2', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
