# Generated by Django 3.2.9 on 2021-12-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_position_option_trade_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position_option',
            name='status',
            field=models.CharField(choices=[('t', 'Take Profit'), ('s', 'Stop loss'), ('w', 'Working')], max_length=1, verbose_name='trade status'),
        ),
    ]
