# Generated by Django 3.2.9 on 2021-12-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_watch_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='coin1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='coin2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='coin',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='watch_list',
            name='coin',
            field=models.CharField(max_length=20),
        ),
    ]
