# Generated by Django 3.2.9 on 2021-12-08 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_position_option_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='user',
            new_name='paper_trading',
        ),
    ]
