# Generated by Django 3.2.9 on 2021-12-16 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20211215_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='paper_trading',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Wallet', to='api.paper_trading', verbose_name='wallet'),
        ),
        migrations.CreateModel(
            name='WalletItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_item', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_item', to='api.wallet')),
            ],
        ),
    ]
