# Generated by Django 3.2.9 on 2021-12-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_user_position_paper_trading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='oreder_reach_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
