# Generated by Django 3.2.9 on 2021-12-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211216_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='coin',
        ),
        migrations.AddField(
            model_name='walletitem',
            name='coin',
            field=models.CharField(default='btc', max_length=20),
        ),
    ]
