# Generated by Django 3.2.9 on 2021-12-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211216_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletitem',
            name='coin',
            field=models.CharField(max_length=20),
        ),
    ]
