# Generated by Django 3.2.9 on 2021-12-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_walletitem_coin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletitem',
            name='user',
        ),
    ]
