# Generated by Django 3.2.9 on 2021-12-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_walletitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletitem',
            old_name='count',
            new_name='amount',
        ),
    ]
